export type ContentGroup = {
  id: string;
  label: string;
  keys: { key: string; label: string; multiline?: boolean }[];
};

export const scaleStatIds = [
  "switches",
  "accessPoints",
  "servers",
  "clients",
] as const;

export const contentGroups: ContentGroup[] = [
  {
    id: "seo",
    label: "SEO",
    keys: [
      { key: "meta.title", label: "Sayfa başlığı" },
      { key: "meta.description", label: "Açıklama", multiline: true },
      { key: "meta.jobTitle", label: "Unvan" },
      { key: "meta.ogRoles", label: "Roller" },
      { key: "meta.keywords", label: "Anahtar kelimeler", multiline: true },
    ],
  },
  {
    id: "hero",
    label: "Hero",
    keys: [
      { key: "hero.index", label: "Üst etiket" },
      { key: "hero.lab", label: "Sağ etiket" },
      { key: "hero.tagline", label: "Açıklama", multiline: true },
      { key: "hero.support", label: "İkinci cümle", multiline: true },
      { key: "hero.roleIt", label: "Rol 1" },
      { key: "hero.roleBuilder", label: "Rol 2" },
      { key: "hero.roleCreator", label: "Rol 3" },
      { key: "hero.scroll", label: "Kaydır yazısı" },
      { key: "hero.scrollHref", label: "Kaydır bağlantısı" },
    ],
  },
  {
    id: "position",
    label: "Konum",
    keys: [
      { key: "position.index", label: "Bölüm etiketi" },
      { key: "position.copy", label: "Metin", multiline: true },
    ],
  },
  {
    id: "system",
    label: "Ölçek",
    keys: [
      { key: "system.index", label: "Bölüm etiketi" },
      { key: "system.title", label: "Başlık" },
      { key: "system.copy", label: "Açıklama", multiline: true },
      { key: "system.switches", label: "Switch etiketi" },
      { key: "system.accessPoints", label: "AP etiketi" },
      { key: "system.servers", label: "Sunucu etiketi" },
      { key: "system.clients", label: "İstemci etiketi" },
    ],
  },
  {
    id: "approach",
    label: "Yaklaşım",
    keys: [
      { key: "approach.index", label: "Bölüm etiketi" },
      { key: "approach.title", label: "Başlık" },
      { key: "approach.copy", label: "Akış" },
      { key: "approach.observe", label: "Observe" },
      { key: "approach.observeCopy", label: "Observe metni", multiline: true },
      { key: "approach.identify", label: "Identify" },
      { key: "approach.identifyCopy", label: "Identify metni", multiline: true },
      { key: "approach.design", label: "Design" },
      { key: "approach.designCopy", label: "Design metni", multiline: true },
      { key: "approach.automate", label: "Automate" },
      { key: "approach.automateCopy", label: "Automate metni", multiline: true },
      { key: "approach.improve", label: "Improve" },
      { key: "approach.improveCopy", label: "Improve metni", multiline: true },
    ],
  },
  {
    id: "work",
    label: "İşler",
    keys: [
      { key: "work.index", label: "Bölüm etiketi" },
      { key: "work.title", label: "Başlık" },
      { key: "work.copy", label: "Açıklama", multiline: true },
      { key: "work.caseStudy", label: "Kart butonu" },
      { key: "work.open", label: "Aç yazısı" },
    ],
  },
  {
    id: "think",
    label: "Bakış",
    keys: [
      { key: "think.index", label: "Bölüm etiketi" },
      { key: "think.title", label: "Başlık" },
      { key: "think.copy", label: "Açıklama", multiline: true },
      { key: "think.group", label: "Grup başlığı" },
      { key: "think.see", label: "İlke 1" },
      { key: "think.seeCopy", label: "İlke 1 metni", multiline: true },
      { key: "think.root", label: "İlke 2" },
      { key: "think.rootCopy", label: "İlke 2 metni", multiline: true },
      { key: "think.beyond", label: "İlke 3" },
      { key: "think.beyondCopy", label: "İlke 3 metni", multiline: true },
      { key: "think.more", label: "Hakkında linki" },
    ],
  },
  {
    id: "lab",
    label: "Lab",
    keys: [
      { key: "lab.index", label: "Bölüm etiketi" },
      { key: "lab.title", label: "Başlık" },
      { key: "lab.copy", label: "Açıklama", multiline: true },
      { key: "lab.experiment", label: "İş sütunu" },
      { key: "lab.status", label: "Durum sütunu" },
      { key: "lab.ref", label: "Ref sütunu" },
      { key: "lab.active", label: "Aktif" },
      { key: "lab.building", label: "Gelişiyor" },
      { key: "lab.experimental", label: "AR-GE" },
    ],
  },
  {
    id: "about",
    label: "Hakkında",
    keys: [
      { key: "about.kicker", label: "Üst etiket" },
      { key: "about.title", label: "Başlık" },
      { key: "about.lead", label: "Giriş", multiline: true },
      { key: "about.careerKicker", label: "Kariyer etiketi" },
      { key: "about.careerTitle", label: "Kariyer başlığı" },
      { key: "about.careerCopy", label: "Kariyer metni", multiline: true },
      { key: "about.leadershipKicker", label: "Yönetim etiketi" },
      { key: "about.leadershipTitle", label: "Yönetim başlığı" },
      { key: "about.leadershipCopy", label: "Yönetim metni", multiline: true },
      { key: "about.leadershipTeam", label: "Ekip" },
      { key: "about.leadershipOps", label: "Operasyon" },
      { key: "about.leadershipProjects", label: "Proje" },
      { key: "about.leadershipCrisis", label: "Kriz" },
      { key: "about.leadershipProcess", label: "Süreç" },
      { key: "about.leadershipVendor", label: "Tedarikçi" },
      { key: "about.impactKicker", label: "Etki etiketi" },
      { key: "about.impactTitle", label: "Etki başlığı" },
      { key: "about.impactOpsTitle", label: "Verimlilik başlığı" },
      { key: "about.impactOpsCopy", label: "Verimlilik metni", multiline: true },
      { key: "about.impactCostTitle", label: "Maliyet başlığı" },
      { key: "about.impactCostCopy", label: "Maliyet metni", multiline: true },
      { key: "about.impactAutoTitle", label: "Otomasyon başlığı" },
      { key: "about.impactAutoCopy", label: "Otomasyon metni", multiline: true },
      { key: "about.impactProcessTitle", label: "Süreç başlığı" },
      { key: "about.impactProcessCopy", label: "Süreç metni", multiline: true },
      { key: "about.lensKicker", label: "Çerçeve etiketi" },
      { key: "about.lensTitle", label: "Çerçeve başlığı" },
      { key: "about.lensCopy", label: "Çerçeve metni", multiline: true },
      { key: "about.peopleTitle", label: "People" },
      { key: "about.peopleCopy", label: "People metni", multiline: true },
      { key: "about.techTitle", label: "Technology" },
      { key: "about.techCopy", label: "Technology metni", multiline: true },
      { key: "about.businessTitle", label: "Business" },
      { key: "about.businessCopy", label: "Business metni", multiline: true },
      { key: "about.philosophyKicker", label: "Yaklaşım etiketi" },
      { key: "about.philosophyTitle", label: "Yaklaşım başlığı" },
      { key: "about.philosophyCopy", label: "Yaklaşım metni", multiline: true },
      { key: "about.beyondKicker", label: "Beyond etiketi" },
      { key: "about.beyondTitle", label: "Beyond başlığı" },
      { key: "about.beyondCopy", label: "Beyond metni" },
    ],
  },
  {
    id: "contact",
    label: "İletişim",
    keys: [
      { key: "contact.index", label: "Bölüm etiketi" },
      { key: "contact.titleLine1", label: "Başlık satır 1" },
      { key: "contact.titleLine2", label: "Başlık satır 2" },
      { key: "contact.copy", label: "Açıklama", multiline: true },
      { key: "contact.email", label: "E-posta etiketi" },
      { key: "contact.linkedin", label: "LinkedIn etiketi" },
      { key: "contact.github", label: "GitHub etiketi" },
    ],
  },
  {
    id: "footer",
    label: "Footer",
    keys: [
      { key: "footer.descriptor", label: "Tanım" },
      { key: "footer.note", label: "Not" },
      { key: "footer.year", label: "Yıl" },
    ],
  },
  {
    id: "project",
    label: "Proje sayfası",
    keys: [
      { key: "project.label", label: "Etiket" },
      { key: "project.category", label: "Kategori" },
      { key: "project.year", label: "Yıl" },
      { key: "project.stack", label: "Stack" },
      { key: "project.problem", label: "Problem" },
      { key: "project.idea", label: "Çözüm" },
      { key: "project.build", label: "Yapılış" },
      { key: "project.technology", label: "Teknoloji" },
      { key: "project.result", label: "Sonuç" },
      { key: "project.open", label: "Aç" },
      { key: "project.previous", label: "Önceki" },
      { key: "project.next", label: "Sonraki" },
    ],
  },
  {
    id: "notFound",
    label: "404",
    keys: [
      { key: "notFound.line1", label: "Satır 1" },
      { key: "notFound.line2", label: "Satır 2" },
      { key: "notFound.back", label: "Geri" },
    ],
  },
  {
    id: "categories",
    label: "Kategoriler",
    keys: [
      { key: "categories.desktop", label: "İzleme" },
      { key: "categories.platform", label: "Platform" },
      { key: "categories.ai", label: "Yapay zeka" },
      { key: "categories.tools", label: "Araçlar" },
    ],
  },
];

export const allContentKeys = contentGroups.flatMap((group) =>
  group.keys.map((item) => item.key),
);

export const skillCategories: { id: string; label: string }[] = [
  { id: "frontend", label: "Frontend" },
  { id: "backend", label: "Backend" },
  { id: "database", label: "Database" },
  { id: "infrastructure", label: "Infrastructure" },
  { id: "tools", label: "Tools" },
];
